---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brevo-credentials
  namespace: ecosystem
spec:
  encryptedData:
    api-key: AgBBf8lEjpdL11ATNbGCeeLN2Xz85Ykll1Ic0NiqmxADKKk87QzaP0LFOisGRVYmIpJojld2jitfB74B3humVArLN4n1uGvT+pWLMm32+mU8bepKEjGe44IyUcHO7bUnt/BvTk9zmw4rbEVsHqghH10qa7W/DX4yEJbBh6eyDKpfy91dvQS+ATN1JKCtLY7dimAtmKizd0jThX9YIQ6+xhJpJxaFr6q56rvgwOVPfuZjm29lJhhOEFqierVIHdlw/k+xyDDHnwp/XZi+k/M1Z8N6WPvUp/ykr2dSXUjM0moHMctcgEliQKVO9vW2x+EqD88pBrxJ2kGnPWG4ZVzVym2gtc8xH83/6IpqT189bTAv7h8sR2sDHdsSAEJACJ0QuFB6lyjQ158qMYuIG8CaXJBzu+mvqDFW2LmFNCiB2y1FWHbLIkirO2UIvsHxmmRvUc34cZErODw1uga8XbIqyg01ZrrGFojV7K5iuPjgSfPBXxDfEPl9P+/zRiDAuQ77EkI2E71gpVA5jUU5Sr36StLlanuEVJWjsjaDcW6r18/CHgbgC8DKXg0pttmDm50DJPw3nUBbrEIp8JxWZQJgxugkVci4eANvhJZUGjWOxkI2uqBVnRAu6PersoxpliosxU3jcAZ+p4chS5VjNj83I4zynTrbacPimbw92Vsrk4uKVInjXfBPCqxS+/2UqBRTs/APHwmmLJ+z329oSxRzpN1NBkzb5+cWmnvsFOESOOQZjXEtTnw8Ile05rNwuhUUoWXgMbwNqIrTb0NYv8U6jhdzE14g7syA8ZOIyXyLuqPsmj/FrT4GQebieQ==
  template:
    metadata:
      name: brevo-credentials
      namespace: ecosystem
