---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: ecosystem
spec:
  encryptedData:
    connection-string: AgAzLTWACFEjyVRX/mJyW9RaPX+TjTQgBGRCSgXuDgneLcXtKe0dhi7lUbeEpmrFMeaAvGtTgC7n33ILe6oUpLIYewIB99L49dpzA37lCXooVY0Zi6cWtQxy9WBaeJVazJoPkgPuus/Yxoqx9ah34TEs73kK/XXGSigokXi78leq1rc7Y5NMVqqN+IUZ0vVIxCWD93+BZ1bf9/Dk+u+InfLRSmBCvH1tHJNEKJfGsPbAk50iuaXkpwETRGQEtQNqdO5KfY2NZOp/B11wGvRu90A1QkSf12E9QiOeQkoOKwlyKV+mbU3ATV1Kk2Anhr+wLzr8gLeTD2aibl8Z3d5/IAp9EaDUyaEVG/YOoSVBUCxsLcAVuyArPbwDqyCkvZ3PaanEd/y4XnMiMhXugWAOrMSmM6NPoS9Ne5kTZNQRoS8fjpfXItXwHLl19LiAO5vATc19Xt2cakokZItVPXo/lKh0IU2UOIfLww9DA44RRSGfcxIb1aRNqBipvGdyuq2tq0r3awPlHdO0Oo2Nz8aG3e7UgQVWxFGlm2r8afk/43Mb2wA+CvfidvZfxSc1aIzH64tr95PSICTa4hRXUOS6qoMTjsqCf9+nOMR58Y/iTo73RjcORCGrd47iqzfCjYnqJgaDCl68Dq2oKT6ojfbD7PrA0Xgf5vCLFFXyldFS8rhk5VkEKjq0E/Om9EMaEGHJz3P+RYdMnbdEFji8dTDjXgMN+kDnpRVn/9/XrNpfONrq2NPLdT+dgv1BLsAkbIGc8msroTIZ+LKWtY/82GcqjNnHEWtWOHfQxhDlDiOakPBYjp91j/eh/mJHJ4Gya6upT67HuaAdpiphrSRApuUgU6K6XpmvmI+ZMDDA4yGrRNzvlvhpCdvcOa7tXa6jbITk4tkSxy5InR06XmJC+X1BlGocQBq7dqZxCVEt
  template:
    metadata:
      name: db-credentials
      namespace: ecosystem
