---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: ecosystem
spec:
  encryptedData:
    connection-string: AgA9/xjR57RqinqA6k63xWR+ReCNIQJhdKweaAs7zQTqh2Ox8thp3SLAQDH6GBRJNSWRYqeP7gcrvkNvv9CJwxqKTw+La/K3l+raUxON4frhynL0fUWkZEmIFoQmPPl4+x3trZJ7+4lCXlrhF9ReFin6R88KcN8YCvnImMeQsLugxe/FuquMLsOcCnqiWaqViXIMBspVBAjB66CC5rdIy8AOwj2gGC6X4B5f3CVSSuUGvF2OvvXEFqmWQa2jpKWkkBdYZ/xgQnHOY16oDzNdrhYP4fe1vPQ0mDkSxA+E6+dTUtYngywn+AXNcE5nG6yWBjKmi6FNWNsgREOofRLMW5PBD2/NYc57ib58Hhv5LvjeSSYGQf9ulIQP4iPzQ3yD6AiWhA09HngQmbmEp0/A3WNA6xkc6qimbPN0ziEF5Zy5Lcogd5x/0jCF86rvtaR0jpMmIH7sVBBCbMyNFnHbIC2VJ8mgINn/x4XI8z4NE369TiK7ALyr17Z9Heq0DSZ7OgfSIH6F6pMl8putVo7pgB/Lyv1BZAxLNZced/JWJ7pVdKhwDXWZDGonu470XvuIhBGhSJJm+MXaiJ3Nns0vdDDDcyF76U81YiloTherxbagAnkfmenMhEM8cQ935mArrLmgpuGiJz23T8dmhDY4Pg5EMjw1/alHOOtN8Y3v3MqnKSQrk6Lv1AKQc5uBWVh6zEg=
  template:
    metadata:
      name: db-credentials
      namespace: ecosystem
