---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: ecosystem
spec:
  encryptedData:
    connection-string: AgACtJptliqxmt1AKHkCydRHcJ6t1SqBTVsaIVbeMhNf9Cq8cqhwNtcuT049h6fRe1sOmm3XVkBh+0s2Gj/6Lv4g7vyb158WftHpoaBusiIFBBHbX4hWPS7CGKyRdPp0babhfAtcIyRLr+G0iKJpUz+vzc+Aori570/EuJfc0EU/YtXQIiFvjrqcL1BdVuQKAgOBS2/M0r7D1d17swJ/i6V4lfS148UUU5i2/bjUXeSusXFWWLIfotJIjAkw8it8wA30Q3k6u2+riblN4Gpw+bu936tXyNCz4y4JlEFd7J97lozjtRVHMNNYRAO7YCE7sGY5I3UMejvs6IsCkZ0Tt8D9Y/LBVlo5P+pWRZ8/iKI99d5+rFuyRzen9KrgEe81CNI/6aw7l4Wl3BJcsvbVGza3ZBFI6yhfTVgoPLgr6/O1GvK8+PbFmajYVrOU011I9nINY7fFTmBPEcVBKIfPotTnkZTYD3+eeifECL/upN9G+Wv462z5y9V8/3FDp90zBzdcenrxgCqoharEzvMysgCHJcel83L9l97UM9JzeRCbbl6PDLM84gQhYcvXw3FO2IAj0YSdxcDoaCZld1ur68WNAyvS1lAUXDmISPJQY5jy8hPel7jw24uc2FE4TVUrogvzwVA3kxmcUUD56/0cp4MnIGjS5vXTOU1mQ/zBIjx+pdLX+R+k8rbEkLvGnJ4EEPipZEtWHvauvmg/0xhCIBtZ4kzgos7Pzc7MLDg/uYx6MiyNVS9pjov2DHQqMmV+Anvl28S+QeoEqNWIrlx0Vg9ourC51FaYGHyAtJ6wohwl5DdMjWkLQC69dbw7P9s8E2lnXOJ7koTqoSX/exxxG0W6MeDYVqi8GyUI1DXIRUXYIWgO1Mc8HBGtr8VS6w3W9Rdaho5l3U3jhAH/aRnc2ybzd6FqWdC0gua9
  template:
    metadata:
      name: db-credentials
      namespace: ecosystem
