apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-credentials
  namespace: ecosystem
spec:
  encryptedData:
    key: AgDkmYI2i7uQtSy2ndAYjIq6WWC9qv+sxm0mQ/56vND6+NvKO0qjDUDS71V5aRYN1ybDkMZ9YqzARPZ8zkCRsYAjcy2FDxAD90Y7nnaSFPSF+xd67YTE3OvkVvttaEWmrz9WDZ3iYy44pEHD6LkOfIytkPcPDQECabwr8uvAFpXq7shL6tmM/BPgUdTbslUyEtiF+z+2nCx3Zt51HGo7doQ5OR3eKxpLjxdfsgwyAv54FpqiRBqK6uffwj1ksk66nw8v6yhFUZ7SHakqUp7/FWP0wP+3BBokFbDVbj4TY/4774Z7aVZ2zfxH29PWo/wlbEDEJJ2ehfnORlCqw7ZUHil5qrW5mKvTDGcw/GTPsouwLmCEfs1Df1xPimz0H2JavNuCrZ7r++VEWvPtxlx9t5gUHIid55Dabvmaah/ghWSLloqFVQyMVeil0QFFxNXDHxYGZ9vmUZiHUv0bDiAt2tmDatwwyPxbXozYUOwBEDZhPzSsivViFKb6fGKRiHDreyzg656MgSJQEIfTen6hNu6k5szUhaoWX+aXfyIUf1mEqg0eGHha1DKmcOYt1GdSv4UnEjVPpaZHIRZIodoz8c7RmCTdYem+NXy9hHHMbbgiZeB0A758SvuEeqt9HpmUOFZxl2emhFEC7HsV8XaoLGDmZhCFVd9MGrfFwbLpgwuzpHywc2e94OUVxhkeeO1eDxDip+4zy4p69PSBJNc5ox01P7U+arIboIZc/qKJUCSlGym+hQwAmyscCaWu8v4zYxc/R3bD5nwMe8knnIqx0JnO+GQa4MGu4mbom53eyP+Td+59xiTmpRBt
  template:
    metadata:
      name: jwt-credentials
      namespace: ecosystem
    type: Opaque
