---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: ecosystem
spec:
  encryptedData:
    connection-string: AgCi32gdGhOxWolFlQ+YMNMLaCm6Sks6Mr6NCCJ69FkvehEJqoHgRYeOW+i+U7sSuipsblP2ECkn18yijOcMs6CzbP6m+h3PG0GwMXiRqSOobQZSe+UkRq06AFV+X0vmDNX8R+j6MKbrJeoVjAJ9Lawre6el5n3ILP3Q1ZPiJ0NEDDbr6DBLd8OswXUfzSNmkkfl59FXO59xCXMQmR79joY4q7sU5MW1WFP6wxaAHJGSZjxsDGjRhR6CJi4hWHCQ7Hz4+Vc8xYsThoxBDBXTkObwxqUIkvSVZntOI2NM7aRK9tXLCqesVt9uj+VCRJD/gPtEub8PyRWMt8NZYuzkLh2F3Ptld0IxP/lKSpaM3iRXcR7Y9FRA1rxNa/w4Dfm0rjj8vUy5d5Uomc7/dtFDKD0znmt/qet7VyhXQNoYsP2JMAtKJiYAABaLfj1K8SOUuLrG0JH3GexBkOnKMxIso7PcRZKilfRRcZOzlsZsJeGCk5GaQV6Ts7LHyEUAYpwc5y1ZmBA6zE6XCCY+VrlPULgR+LS0oYD8ssc6PSaPuEOdFoykC6YQq7rxzmMhcRN94UavOWWvyZHbNWZxmttjN4Eug0Zzo06dwOIejJXwoO27sLLGNSU5Sd6lro/vbDJCvZUFGaA1Q8IvC7HauJF1DQ0HbWDmz7X6odnPO9RrfAlr2IoAHAnB8Z3u7+yuLZjJxUmKPSGUPD5nO9LCO48ijkZSlx04n2HNl5kxvMyU77uvgw3B/CptdMCpOvEKE5ZSbusVNrZf6e6W9K4w+8VxkPG89HtjAHSDG8ycxxXQ8CGyRq+lRW72+FgAGj7oCt+2khmlofM5uhmtMDesKlTunh0ybn+54gq10xI6A9VKHL/kbprgQNk0moZdt+kX
  template:
    metadata:
      name: redis-credentials
      namespace: ecosystem
