---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: spaces-credentials
  namespace: ecosystem
spec:
  encryptedData:
    access-key: AgAqaScPAinSl4uJRGC1gS/k8PDgmSNe9pXZ+Y9UJz+Tri5DrULztDl7RQM939jNAIJOhlHnagANPdGOgeFQ7jDd9CXVfawQSXdRdCaR7/3YqL5z7cSfJ5uhIv6Dfq+BWu2aEX6Cic8/CkKhVhPxSvFVcsPdEIXby4AwcoqMpE6QzjIaJbgSwAHoIcB/QI9j72Tt4SivG9h75Ob+HXzjqo+ECFX0StDWdjCsqUf84EgdspohMRVrpTz9w+TXtb4B6UVev4A62vgrx25IaUjx5rmsy+e2ft0iaF3nu/M+Rodr2YpgTUFZ1JPyaWzW59eJf+da/rlMJuc/0PXVGa9OI2ada6673ClkBOmQvQSaRcTYUy/663+XlTpupIILnreOhXedLHl238qV3xGpW6aYMKeR3mOPXgV4CU9xLKOM+Yi/ayVbJmsy7+G1WvyXtlZ3M/fuZEsq5eoPvGUs0LYIE/fmmkFz4VaolRPczqsbKNqpOWfJvimidFIMhcTzY/Oonw6wvHiG00EMHVKULrk5qvLunlyyEonpXaceHuWue5HeeGmZsdWnWJJupks+VCys7Ech/nKg1NyBrJ7+ezjra3fz/J1zHgwMxU+1r9h5T2DdSnQSAyhIk1AV/Y7oD3Lz4dy26Pg/2odG4a6i4h80uEMowimPClfFtsytWUPDW6ka1amMDTAJMjwYr+sTakL3mKTclnxmFdQMbpT5zFmz+TbMtJ0H+Q==
    secret-key: AgCHapp2glJxZP9vES1aVop5Z5Ru9s3gsd0vvLV3Wc5mKYaHmn1QtF6pvKItJIYhUYAE8RC0Gd9G22Cxk1FHIasvYLs82kwxZoh293KFi0V0ObKt0e9K2hBj/0cOye12nV/nhc60E/S/8fX2MJqvp4QjpLHofyzGqGTZOxS+fVHOufVkI3YIy5sO2H7RfJJal5zs4r+Fhq31sliFkS+K8x64da3zvpbeU2ca5kxflriZokB9H7+A5AX4mdtoogWCvCwpylyeNo6K8jeHTd6jgUWLyqiC1vsAdin+CfCa9RqlU4J+Ob7PAoPRgRlJA7iOA1jCYP82YqfTWRrFmEcO4m87W5ydzRZyeM1WiPWcB0rYiXw3X0hIIOB/3sVvffzqnd4vFd1dd/aMP4nJfzUAuHACeW9si5HL+/LrTBVFh5E2tCms0UdZuIMt43njJuQGv7Nxf3KmAEKNiA7lf64mCTEtyfz2z3u1oVqTkgpCnQ89UQ4XA5cXiu4nt9/f0vdiNDKUe1KzxrY52tF011CQVNrOZXNNzS1jxurjZP3ctSlGEMPvUC1QUMCeFf36yDArjd0cn9rYBOoUvKAlHHJNShZSKhAfX2xyTBZM/7D4lUmY46kRXRHFLYjy0V2XF7XFUrEsfo/3s4pO8n8is7nsZdhv4xmP5ew/zlbDfPdj+rOwtslI+Jov95cTmYuVd9nlxomUmdATCKzi4917fbVP0UcJHArmS1h24wVfFbXKa7vwiMsnPVs/HNhPBaOo
  template:
    metadata:
      name: spaces-credentials
      namespace: ecosystem
