apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ecosystem
  source:
    repoURL: https://github.com/Ocx-Group/ecosystem-microservices
    targetRevision: main
    path: Infrastructure/k8s/sealed-secrets
    directory:
      recurse: false
      include: '*.yaml'
      exclude: 'README.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: ecosystem
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
