// <auto-generated />
using System;
using Ecosystem.ConfigurationService.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecosystem.ConfigurationService.Data.Migrations
{
    [DbContext(typeof(ConfigurationServiceDbContext))]
    [Migration("20260814190023_AddMonthlyCommissionSource")]
    partial class AddMonthlyCommissionSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.ApiClient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('apiclient_id_seq'::regclass)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("idx_17090_pk__apiclien__3214ec073dd66e87");

                    b.ToTable("api_client", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.Bank", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('banks_id_seq'::regclass)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("idx_17104_pk__banks__3214ec0774204b7a");

                    b.ToTable("banks", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.BankDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('bankdetails_id_seq'::regclass)");

                    b.Property<string>("Api")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api");

                    b.Property<long>("BankId")
                        .HasColumnType("bigint")
                        .HasColumnName("bank_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("idx_17097_pk__bankdeta__3214ec07af03088a");

                    b.HasIndex("BankId");

                    b.ToTable("bank_details", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('brand_id_seq'::regclass)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("idx_17111_pk__brand__3214ec07f9703688");

                    b.HasIndex(new[] { "IsActive" }, "idx_17111_ix_brand_isactive")
                        .HasFilter("(is_active = true)");

                    b.HasIndex(new[] { "Name" }, "idx_17111_ix_brand_name");

                    b.HasIndex(new[] { "SecretKey" }, "idx_17111_uq_brand_secretkey")
                        .IsUnique();

                    b.ToTable("brand", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.BrandConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('brand_configuration_id_seq'::regclass)");

                    b.Property<bool>("ActivateOnRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("activate_on_registration")
                        .HasDefaultValueSql("true");

                    b.Property<string>("AdminUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admin_user_name");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("background_color");

                    b.Property<int?>("BlockchainNetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("blockchain_network_id");

                    b.Property<decimal>("BonusPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("bonus_percentage")
                        .HasDefaultValueSql("0");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<string>("ClientUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_url");

                    b.Property<bool>("CommissionEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("commission_enabled");

                    b.Property<string>("CommissionLevelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("commission_levels");

                    b.Property<string>("CompanyIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("company_identifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("ConPaymentAddress")
                        .HasColumnType("text")
                        .HasColumnName("con_payment_address");

                    b.Property<bool>("ConPaymentEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("con_payment_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("DailyBonusAlwaysDistribute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("daily_bonus_always_distribute")
                        .HasDefaultValueSql("false");

                    b.Property<int?>("DefaultFatherAffiliateId")
                        .HasColumnType("integer")
                        .HasColumnName("default_father_affiliate_id");

                    b.Property<int?>("DefaultPaymentGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("default_payment_group_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<string>("EmailTemplateFolder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_template_folder");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("true");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<bool>("MonthlyCommissionEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("monthly_commission_enabled")
                        .HasDefaultValueSql("false");

                    b.Property<decimal>("MonthlyCommissionInterestRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("monthly_commission_interest_rate")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("MonthlyCommissionPaymentGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_commission_payment_group_id");

                    b.Property<string>("MonthlyCommissionSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("monthly_commission_source")
                        .HasDefaultValueSql("'PaymentGroup'");

                    b.Property<int>("MonthlyCommissionWaitingDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("monthly_commission_waiting_days")
                        .HasDefaultValueSql("0");

                    b.Property<string>("PdfTemplateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pdf_template_name");

                    b.Property<bool>("PoolValidationRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("pool_validation_required");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_color");

                    b.Property<bool>("Requires10PercentPurchaseRule")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_10_percent_purchase_rule");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secondary_color");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_email");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_name");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("support_email");

                    b.Property<string>("SupportPhone")
                        .HasColumnType("text")
                        .HasColumnName("support_phone");

                    b.Property<int?>("TradingAcademyPaymentGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("trading_academy_payment_group_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("WithdrawalCapNoDirects")
                        .HasColumnType("numeric")
                        .HasColumnName("withdrawal_cap_no_directs");

                    b.Property<int?>("WithdrawalEndHour")
                        .HasColumnType("integer")
                        .HasColumnName("withdrawal_end_hour");

                    b.Property<int?>("WithdrawalStartHour")
                        .HasColumnType("integer")
                        .HasColumnName("withdrawal_start_hour");

                    b.Property<string>("WithdrawalTimeZone")
                        .HasColumnType("text")
                        .HasColumnName("withdrawal_time_zone");

                    b.Property<string>("WithdrawalValidationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("None")
                        .HasColumnName("withdrawal_validation_type");

                    b.HasKey("Id")
                        .HasName("brand_configuration_pkey");

                    b.HasIndex(new[] { "BrandId" }, "idx_brand_configuration_brand_id")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("brand_configuration", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.ConceptConfigurations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('conceptconfigurations_id_seq'::regclass)");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<bool>("Compression")
                        .HasColumnType("boolean")
                        .HasColumnName("compression");

                    b.Property<long>("ConceptId")
                        .HasColumnType("bigint")
                        .HasColumnName("concept_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Equalization")
                        .HasColumnType("integer")
                        .HasColumnName("equalization");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric")
                        .HasColumnName("percentage");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("idx_17120_pk__conceptc__3214ec07f83e8c12");

                    b.HasIndex("ConceptId");

                    b.ToTable("concept_configurations", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.Concepts", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('concepts_id_seq'::regclass)");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("active")
                        .HasDefaultValueSql("true");

                    b.Property<string>("BinaryGrades")
                        .HasColumnType("text")
                        .HasColumnName("binary_grades");

                    b.Property<decimal>("BinaryPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("binary_percentage")
                        .HasDefaultValueSql("0.00");

                    b.Property<string>("BinaryProductsGroup")
                        .HasColumnType("text")
                        .HasColumnName("binary_products_group");

                    b.Property<decimal>("BinaryTop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("binary_top")
                        .HasDefaultValueSql("0.00");

                    b.Property<int>("BinaryTopInfinity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("binary_top_infinity")
                        .HasDefaultValueSql("1");

                    b.Property<int>("BinaryType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("binary_type")
                        .HasDefaultValueSql("1");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<int>("CalculateBy")
                        .HasColumnType("integer")
                        .HasColumnName("calculate_by");

                    b.Property<bool>("Compression")
                        .HasColumnType("boolean")
                        .HasColumnName("compression");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateConcept")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_concept");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Equalization")
                        .HasColumnType("boolean")
                        .HasColumnName("equalization");

                    b.Property<bool>("IgnoreActivationOrder")
                        .HasColumnType("boolean")
                        .HasColumnName("ignore_activation_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PayConcept")
                        .HasColumnType("integer")
                        .HasColumnName("pay_concept");

                    b.Property<long>("PaymentGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_group_id");

                    b.Property<bool?>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("status")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("idx_17128_pk__concepts__3214ec07928d73ac");

                    b.HasIndex("PaymentGroupId");

                    b.ToTable("concepts", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.Configurations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('configurations_id_seq'::regclass)");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("idx_17144_pk__configur__3214ec07045d7c26");

                    b.ToTable("configurations", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.Gradings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('gradings_id_seq'::regclass)");

                    b.Property<int>("ActivateUserBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("activate_user_by")
                        .HasDefaultValueSql("1");

                    b.Property<int>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("active")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("Affiliations")
                        .HasColumnType("integer")
                        .HasColumnName("affiliations");

                    b.Property<decimal>("BinaryVolume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("binary_volume")
                        .HasDefaultValueSql("0.00");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<int>("ChildrenLeftLeg")
                        .HasColumnType("integer")
                        .HasColumnName("children_left_leg");

                    b.Property<int>("ChildrenRightLeg")
                        .HasColumnType("integer")
                        .HasColumnName("children_right_leg");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("ExactFrontRatings")
                        .HasColumnType("boolean")
                        .HasColumnName("exact_front_ratings");

                    b.Property<int>("FrontByMatrix")
                        .HasColumnType("integer")
                        .HasColumnName("front_by_matrix");

                    b.Property<int>("FrontQualif1")
                        .HasColumnType("integer")
                        .HasColumnName("front_qualif1");

                    b.Property<int>("FrontScore1")
                        .HasColumnType("integer")
                        .HasColumnName("front_score1");

                    b.Property<int>("FrontScore2")
                        .HasColumnType("integer")
                        .HasColumnName("front_score2");

                    b.Property<int>("FrontScore3")
                        .HasColumnType("integer")
                        .HasColumnName("front_score3");

                    b.Property<int>("Frontqualif2")
                        .HasColumnType("integer")
                        .HasColumnName("frontqualif2");

                    b.Property<int>("Frontqualif3")
                        .HasColumnType("integer")
                        .HasColumnName("frontqualif3");

                    b.Property<bool>("FullPeriod")
                        .HasColumnType("boolean")
                        .HasColumnName("full_period");

                    b.Property<bool>("HaveBoth")
                        .HasColumnType("boolean")
                        .HasColumnName("have_both");

                    b.Property<bool>("IsInfinity")
                        .HasColumnType("boolean")
                        .HasColumnName("is_infinity");

                    b.Property<int>("LeaderByMatrix")
                        .HasColumnType("integer")
                        .HasColumnName("leader_by_matrix");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NetworkLeaders")
                        .HasColumnType("integer")
                        .HasColumnName("network_leaders");

                    b.Property<int?>("NetworkLeadersQualifier")
                        .HasColumnType("integer")
                        .HasColumnName("network_leaders_qualifier");

                    b.Property<int>("NetworkScopeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("network_scope_level");

                    b.Property<decimal>("PersonalPurchases")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("personal_purchases")
                        .HasDefaultValueSql("0.00");

                    b.Property<bool>("PersonalPurchasesExact")
                        .HasColumnType("boolean")
                        .HasColumnName("personal_purchases_exact");

                    b.Property<int?>("Products")
                        .HasColumnType("integer")
                        .HasColumnName("products");

                    b.Property<decimal>("PurchasesNetwork")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("purchases_network")
                        .HasDefaultValueSql("0.00");

                    b.Property<int>("ScopeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("scope_level");

                    b.Property<bool?>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("status")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VolumePoints")
                        .HasColumnType("integer")
                        .HasColumnName("volume_points");

                    b.Property<int>("VolumePointsNetwork")
                        .HasColumnType("integer")
                        .HasColumnName("volume_points_network");

                    b.HasKey("Id")
                        .HasName("idx_17151_pk__gradings__3214ec07da63777c");

                    b.ToTable("gradings", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.Incentives", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('incentives_id_seq'::regclass)");

                    b.Property<int>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("active")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("Affiliations")
                        .HasColumnType("integer")
                        .HasColumnName("affiliations");

                    b.Property<decimal>("BinaryVolume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("binary_volume")
                        .HasDefaultValueSql("0.00");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<int>("ChildrenLeftLeg")
                        .HasColumnType("integer")
                        .HasColumnName("children_left_leg");

                    b.Property<int>("ChildrenRightLeg")
                        .HasColumnType("integer")
                        .HasColumnName("children_right_leg");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("ExactFrontRatings")
                        .HasColumnType("boolean")
                        .HasColumnName("exact_front_ratings");

                    b.Property<int>("FrontByMatrix")
                        .HasColumnType("integer")
                        .HasColumnName("front_by_matrix");

                    b.Property<int>("FrontQuali2")
                        .HasColumnType("integer")
                        .HasColumnName("front_quali2");

                    b.Property<int>("FrontQualif1")
                        .HasColumnType("integer")
                        .HasColumnName("front_qualif1");

                    b.Property<int>("FrontQualif3")
                        .HasColumnType("integer")
                        .HasColumnName("front_qualif3");

                    b.Property<int>("FrontScore1")
                        .HasColumnType("integer")
                        .HasColumnName("front_score1");

                    b.Property<int>("FrontScore2")
                        .HasColumnType("integer")
                        .HasColumnName("front_score2");

                    b.Property<int>("FrontScore3")
                        .HasColumnType("integer")
                        .HasColumnName("front_score3");

                    b.Property<int?>("Grading")
                        .HasColumnType("integer")
                        .HasColumnName("grading");

                    b.Property<bool>("IsInfinity")
                        .HasColumnType("boolean")
                        .HasColumnName("is_infinity");

                    b.Property<int>("LeaderByMatrix")
                        .HasColumnType("integer")
                        .HasColumnName("leader_by_matrix");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NetworkLeaders")
                        .HasColumnType("integer")
                        .HasColumnName("network_leaders");

                    b.Property<int?>("NetworkLeadersQualifier")
                        .HasColumnType("integer")
                        .HasColumnName("network_leaders_qualifier");

                    b.Property<decimal>("PersonalPurchases")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("personal_purchases")
                        .HasDefaultValueSql("0.00");

                    b.Property<bool>("PersonalPurchasesExact")
                        .HasColumnType("boolean")
                        .HasColumnName("personal_purchases_exact");

                    b.Property<int?>("Products")
                        .HasColumnType("integer")
                        .HasColumnName("products");

                    b.Property<decimal>("PurchasesNetwork")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("purchases_network")
                        .HasDefaultValueSql("0.00");

                    b.Property<int>("ScopeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("scope_level");

                    b.Property<bool?>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("status")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VolumePoints")
                        .HasColumnType("integer")
                        .HasColumnName("volume_points");

                    b.Property<int>("VolumePointsNetwork")
                        .HasColumnType("integer")
                        .HasColumnName("volume_points_network");

                    b.HasKey("Id")
                        .HasName("idx_17183_pk__incentiv__3214ec07093230c1");

                    b.ToTable("incentives", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.MatrixConfiguration", b =>
                {
                    b.Property<int>("MatrixType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("matrix_type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatrixType"));

                    b.Property<int>("ChildCount")
                        .HasColumnType("integer")
                        .HasColumnName("child_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("fee_amount");

                    b.Property<int>("Levels")
                        .HasColumnType("integer")
                        .HasColumnName("levels");

                    b.Property<string>("MatrixName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matrix_name");

                    b.Property<decimal>("MaxWithdraw")
                        .HasColumnType("numeric")
                        .HasColumnName("max_withdraw");

                    b.Property<decimal>("MinWithdraw")
                        .HasColumnType("numeric")
                        .HasColumnName("min_withdraw");

                    b.Property<decimal>("RangeMax")
                        .HasColumnType("numeric")
                        .HasColumnName("range_max");

                    b.Property<decimal>("RangeMin")
                        .HasColumnType("numeric")
                        .HasColumnName("range_min");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("numeric")
                        .HasColumnName("threshold");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MatrixType")
                        .HasName("matrix_config_pkey");

                    b.ToTable("matrix_config", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.PaidConcept", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('paidconcepts_id_seq'::regclass)");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<long>("ConceptId")
                        .HasColumnType("bigint")
                        .HasColumnName("concept_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("idx_17211_pk__paidconc__3214ec073602c932");

                    b.HasIndex("ConceptId");

                    b.ToTable("paid_concepts", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.PaymentGroups", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('paymentgroups_id_seq'::regclass)");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("idx_17218_pk__paymentg__3214ec07f79b91ee");

                    b.ToTable("payment_groups", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.PdfTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('pdf_template_id_seq'::regclass)");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brand_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CssContent")
                        .HasColumnType("text")
                        .HasColumnName("css_content");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_content");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("true");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("template_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("version")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id")
                        .HasName("pdf_template_pkey");

                    b.HasIndex(new[] { "BrandId", "TemplateKey" }, "idx_pdf_template_brand_key")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("pdf_template", "configuration_service");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.BankDetail", b =>
                {
                    b.HasOne("Ecosystem.ConfigurationService.Domain.Models.Bank", "Bank")
                        .WithMany("BankDetails")
                        .HasForeignKey("BankId")
                        .IsRequired()
                        .HasConstraintName("fk_bankdetails_banks");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.BrandConfiguration", b =>
                {
                    b.HasOne("Ecosystem.ConfigurationService.Domain.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_brand_configuration_brand");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.ConceptConfigurations", b =>
                {
                    b.HasOne("Ecosystem.ConfigurationService.Domain.Models.Concepts", "Concepts")
                        .WithMany("ConceptConfigurations")
                        .HasForeignKey("ConceptId")
                        .IsRequired()
                        .HasConstraintName("fk_concept_concept_configuration");

                    b.Navigation("Concepts");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.Concepts", b =>
                {
                    b.HasOne("Ecosystem.ConfigurationService.Domain.Models.PaymentGroups", "PaymentGroups")
                        .WithMany("Concepts")
                        .HasForeignKey("PaymentGroupId")
                        .IsRequired()
                        .HasConstraintName("fk_concepts_paymentgroups");

                    b.Navigation("PaymentGroups");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.PaidConcept", b =>
                {
                    b.HasOne("Ecosystem.ConfigurationService.Domain.Models.Concepts", "Concepts")
                        .WithMany("PaidConcepts")
                        .HasForeignKey("ConceptId")
                        .IsRequired()
                        .HasConstraintName("fk_paidconcepts_concepts");

                    b.Navigation("Concepts");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.PdfTemplate", b =>
                {
                    b.HasOne("Ecosystem.ConfigurationService.Domain.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pdf_template_brand");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.Bank", b =>
                {
                    b.Navigation("BankDetails");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.Concepts", b =>
                {
                    b.Navigation("ConceptConfigurations");

                    b.Navigation("PaidConcepts");
                });

            modelBuilder.Entity("Ecosystem.ConfigurationService.Domain.Models.PaymentGroups", b =>
                {
                    b.Navigation("Concepts");
                });
#pragma warning restore 612, 618
        }
    }
}
